export const GET_ALL_POSTS_WITH_FILTER_SUCCESS = 'GET_ALL_POSTS_WITH_FILTER_SUCCESS';
export const GET_ALL_POSTS_WITHOUT_FILTER_SUCCESS = 'GET_ALL_POSTS_WITHOUT_FILTER_SUCCESS';
export const FAILURE_TO_GET_POSTS = 'FAILURE_TO_GET_POSTS';
export const GET_ONE_POST = 'GET_ONE_POST';
export const FETCHING_SOURCES = 'FETCHING_SOURCES';
export const GET_ALL_SOURCES_SUCCESS = 'GET_ALL_SOURCES_SUCCESS';
export const GET_ALL_SOURCES_FAILURE = 'GET_ALL_SOURCES_FAILURE';
